### PR TITLE
EventToCommand topic

### PR DESCRIPTION
**Pull request by MichaelPonti**
Hi @brianlagunas , first draft on this. I think it is ok, but perhaps you want like something additional in there.

Thanks!

### CODE REVIEW

**Comment by brianlagunas** [comment]
Actually, if would be better if you could follow something similar to this

https://prismlibrary.com/docs/xamarin-forms/behaviors/eventtocommandbehavior.html

**Comment by MichaelPonti** [comment]
Sorry for the delay. Things have kind of gone off the deep end at work. I will see if I can look at it this weekend.

**Comment by MichaelPonti** [comment]
hi @brianlagunas, reworked to match XF. Let me know what you think.
Thanks!

**Comment by brianlagunas** [comment]
Looks great. Thanks again! You rock!

**Pull request merged**
