### PR TITLE
Prism 9 Updates

### PR DESCRIPTION
**Pull request by dansiegel**
# Description

Providing an overhaul to the layout to bring topics to the core as we have shifted many of the concerns away from the platforms and to the Prism.Core or made additional efforts to decouple some concepts such as DI from the platforms and from Prism.Core.

### CODE REVIEW

**Comment by adegeo** [comment]
@dansiegel This is a bit disappointing. What should I do about WPF documentation that links to this content? Is this stuff not archived anywhere?

**Comment by dansiegel** [comment]
@adegeo what exactly is disappointing? Please feel free to email me dan@prismlibrary.com to discuss how this affects the WPF docs...

**Comment by adegeo** [comment]
I just hate to see docs and things disappear into the void 😁 Sure I'll email you

**Comment by adegeo** [comment]
Ahhhh my mistake. For some reason I was under the impression that WPF was being dropped as "legacy.." I see that it's the old version of Prism that's dropped from docs. Though it would be nice to have them archived somewhere 😁

Might I suggest adding a tag to the repo at that commit so that the old legacy content is easily browsable?

**Pull request merged**
