### PR TITLE
Update viewmodel-locator.md

### PR DESCRIPTION
**Pull request by SungracePrashant**
Updated link was not working hence I updated it.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/PrismLibrary/Prism-Documentation?pullRequest=100) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/PrismLibrary/Prism-Documentation?pullRequest=100) before we can accept your contribution.<br/><br/>:x: SungracePrashant [sign now](https://cla.dotnetfoundation.org/PrismLibrary/Prism-Documentation?pullRequest=100)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/PrismLibrary/Prism-Documentation?pullRequest=100) it.</sub>

**Comment by SungracePrashant** [comment]
Please make changes.
It is a small change only.

**Comment by dansiegel** [comment]
@SungracePrashant we'd be happy to take the PR if you'd like to reopen it and sign the .NET Foundation CLA. The CLA is required for all .NET Foundation projects and you only need to sign it on your first PR and it will stay with you for any other PR's you do on any member projects :)

**Comment by prashantbaher** [comment]
@dansiegel I will open a new PR, by mistake I used my company provided account not personal.

**Pull request closed without merging**
