### PR TITLE
Update to match sample code

### PR DESCRIPTION
**Pull request by MikeEsteves**
Change from assembly annotations to specific registration 
Replace Win Phone example with UWP example
Update link to sample

### CODE REVIEW

**Comment by brianlagunas** [comment]
Thanks, but this is a dead topic. It was kept around for a "How To" topic around registering platform specific services. We just haven't gotten around to structuring the docs for these types of topics.

**Comment by dansiegel** [comment]
@brianlagunas if you look closely this is actually going in the right direction here... There is still some changes that are needed though. This is a good start in changing from discussing the deprecated DependencyService and is showing using IPlatformInitializer. That said we do need some additional changes here. I'll try to notate that in a bit.

**Comment by MikeEsteves** [comment]
From someone relatively new to Prism dead topics are worse than no existing topics or just links to samples. Or at least have a "This works with version X". Following an official topic only to find it doesn't work isn't great. 

Anyways happy to make further changes as needed. If you follow the topic as of this pull it at least works so it's in a better place than currently

**Comment by brianlagunas** [comment]
@ScarlettCode how did you even navigate to this topic? It's not in the documentation navigation. Maybe a link from some where?

**Comment by MikeEsteves** [comment]
@brianlagunas "prism xamarin call native code" google first result. But fair point about it not being in the documentation navigation. Didn't even notice that. Got to it via google and because it's from the docs site just assumed it was valid

**Comment by brianlagunas** [comment]
Ahhhhh.. thanks. We should rename the title of the topic closer to the phrase you googled :)

**Comment by dansiegel** [comment]
Closing this as ultimately the Dependency Service topic is deprecated and should be removed. The only real discussion that needs to occur for Platform Specific code is all about IPlatformInitializer.

**Pull request closed without merging**
