### PR TITLE
First run at modularity

### PR DESCRIPTION
**Pull request by MichaelPonti**
@brianlagunas , modularity first draft. I tried to keep it pretty simple, but please let me know if you want additional content to be included.

### CODE REVIEW

**Comment by brianlagunas** [comment]
For specific topics such as Modularity, we need to focus on just the functionality of the feature. For example, we need to explain modularity, then show how to create modules, then show how to register modules using all supported approaches.  All samples should point to the official Prism samples repo: https://github.com/PrismLibrary/Prism-Samples-Wpf

A good source of information to help is the legacy docs: https://prismlibrary.com/docs/wpf/legacy/Modules.html

**Comment by MichaelPonti** [comment]
Ok, thanks Brian, I will re-work it.

**Comment by MichaelPonti** [comment]
Hi @brianlagunas , I reworked modularity as per your direction. Mostly I re-used the legacy, just removing any last silverlight,  references to old containers, bootstrappers etc. Please review when you have a moment. Thanks!

**Comment by brianlagunas** [comment]
works for me, thanks a lot!

**Pull request merged**
