### PR TITLE
07 Composing the UI in Chinese

### PR DESCRIPTION
**Pull request by mamta345**
07 Composing the UI in Chinese(part)
to be continued.

### CODE REVIEW

**Comment by bobdog1986** [comment]
support...

**Comment by brianlagunas** [comment]
Great job, keep it coming

**Comment by guyichang** [comment]
Great job, keep it coming

**Comment by brianlagunas** [comment]
There hasn't been any movement on this issue. I know your intentions were good, and probably just couldn't find the time to continue.  Also, this content has been placed as legacy and we will be rewriting the WPF docs for the newest version

**Pull request closed without merging**
