### PR TITLE
Small updates to introduction.md

### PR DESCRIPTION
**Pull request by DarqueWarrior**

### CODE REVIEW

**Comment by DarqueWarrior** [comment]
When will http://prismlibrary.github.io/docs/wpf/Introduction.html be updated with these changes?

**Comment by brianlagunas** [comment]
We are using docfx so I have to manually build them and copy the files over to our GitHub pages. I'll try to get this out this week.

**Comment by brianlagunas** [comment]
As you can see, we haven't implemented any build automation on the docs side of things yet :)

**Comment by dansiegel** [comment]
wonder if @DarqueWarrior knows a thing or two about build automation haha

**Comment by brianlagunas** [comment]
I doubt it. Don't worry, I know a guy at my local doughnut shop that says he took a computer class in high school. He would be happy to help. I hear he's rimaculous!

**Comment by DarqueWarrior** [comment]
When I get off the road we should take a look at this.

**Comment by brianlagunas** [comment]
Yes we should. Just let me know when you're back at home base.

**Pull request merged**
