### PR TITLE
Update creating-your-first-prism-app.md

### PR DESCRIPTION
**Pull request by andersnicolai**
Just fixed a typo

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/PrismLibrary/Prism-Documentation?pullRequest=85) <br/>All CLA requirements met.

**Comment by brianlagunas** [comment]
We can't merge this unless the CLA has been signed. Once you sign it I can merge your PR. Thanks

**Comment by dansiegel** [comment]
@andersnicolai we'd be happy to take this PR, however we do need you to sign the .NET Foundation CLA. This applies to all .NET Foundation projects so you'll only ever have to sign it once :)

**Comment by andersnicolai** [comment]
Hi friends, have I done the correct steps for signing the .NET foundation CLA by now?

**Comment by andersnicolai** [comment]
alright, now all should be good. Thank  you guys for making Prism <3 Hope I also can contribute to the code the more I get my hands dirty with it.

**Pull request merged**
